version: '3.8'
services:
  php:
    container_name: php84
    image: ghcr.io/xiaohuangtx/php84:latest
    restart: always
    privileged: true
    ports:
      - "9000:9000"
    volumes:
      - "./www:/var/www/html"
      
